"""create tables

Revision ID: 3168445b1ed5
Revises: 
Create Date: 2023-02-26 15:25:56.983999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3168445b1ed5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('mileage', sa.BigInteger(), nullable=False),
    sa.Column('measures', sa.String(length=15), nullable=False),
    sa.Column('date_added', sa.TIMESTAMP(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_mileage', sa.BigInteger(), nullable=False),
    sa.Column('fk_users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tg_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_users_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=50), nullable=False),
    sa.Column('tg_firstname', sa.String(length=50), nullable=True),
    sa.Column('tg_lastname', sa.String(length=50), nullable=True),
    sa.Column('fk_users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_users')
    op.drop_table('cars')
    op.drop_table('users')
    # ### end Alembic commands ###
