"""create tables

Revision ID: 5924a78b2469
Revises: 3168445b1ed5
Create Date: 2023-02-26 15:47:28.728474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5924a78b2469'
down_revision = '3168445b1ed5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
